"""
historical_storage.py
---------------------
SQLite persistence layer for historical market data and price series.

Tables:
  historical_markets  – one row per resolved market (from Gamma API)
  historical_prices   – hourly/6h price bars per market token (from CLOB)
  historical_snapshots – virtual watchlist snapshots generated by the
                         snapshot builder (one per market per time point)

The database is kept separate from watchlist.sqlite to avoid polluting
the live shadow bot state.
"""

from __future__ import annotations

import json
import sqlite3
from contextlib import closing
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from bot.historical_fetcher import HistoricalMarket, HistoricalPriceBar


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

_DDL = """\
CREATE TABLE IF NOT EXISTS historical_markets (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    market_id       TEXT UNIQUE NOT NULL,
    slug            TEXT,
    question        TEXT,
    description     TEXT,
    category        TEXT,
    end_date        TEXT,
    closed_time     TEXT,
    volume          REAL,
    yes_token_id    TEXT,
    no_token_id     TEXT,
    outcome_yes     REAL,
    outcome_no      REAL,
    event_type      TEXT,
    platform        TEXT,
    raw_json        TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS historical_prices (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    market_id       TEXT NOT NULL,
    token_side      TEXT NOT NULL,
    timestamp_utc   TEXT NOT NULL,
    open_price      REAL,
    high_price      REAL,
    low_price       REAL,
    close_price     REAL,
    UNIQUE(market_id, token_side, timestamp_utc)
);

CREATE TABLE IF NOT EXISTS historical_snapshots (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    market_id           TEXT NOT NULL,
    slug                TEXT,
    timestamp_utc       TEXT NOT NULL,
    days_before_close   REAL,
    event_type          TEXT,
    platform            TEXT,
    yes_mid             REAL,
    no_mid              REAL,
    yes_ask             REAL,
    no_ask              REAL,
    yes_bid             REAL,
    no_bid              REAL,
    spread              REAL,
    p_model             REAL,
    model_side          TEXT,
    net_edge            REAL,
    max_entry_price     REAL,
    market_ok           INTEGER,
    signal_ok           INTEGER,
    outcome_yes         REAL,
    outcome_no          REAL,
    raw_json            TEXT,
    UNIQUE(market_id, timestamp_utc)
);

CREATE INDEX IF NOT EXISTS idx_hist_prices_market ON historical_prices(market_id, token_side);
CREATE INDEX IF NOT EXISTS idx_hist_snapshots_market ON historical_snapshots(market_id);
CREATE INDEX IF NOT EXISTS idx_hist_snapshots_ts ON historical_snapshots(timestamp_utc);
"""


# ---------------------------------------------------------------------------
# HistoricalStore class
# ---------------------------------------------------------------------------

class HistoricalStore:
    def __init__(self, db_path: str) -> None:
        self.db_path = db_path
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        with closing(sqlite3.connect(db_path)) as conn:
            conn.executescript(_DDL)
            conn.commit()

    # -----------------------------------------------------------------------
    # historical_markets
    # -----------------------------------------------------------------------

    def insert_markets(
        self,
        markets: list[HistoricalMarket],
        event_type_map: dict[str, str] | None = None,
        platform_map: dict[str, str] | None = None,
    ) -> int:
        """Insert or ignore markets. Returns number of newly inserted rows."""
        event_type_map = event_type_map or {}
        platform_map = platform_map or {}
        rows = [
            (
                market.market_id,
                market.slug,
                market.question,
                market.description,
                market.category,
                _iso(market.end_date),
                _iso(market.closed_time),
                market.volume,
                market.yes_token_id,
                market.no_token_id,
                market.outcome_yes,
                market.outcome_no,
                event_type_map.get(market.market_id),
                platform_map.get(market.market_id),
                json.dumps(market.raw, ensure_ascii=True),
            )
            for market in markets
        ]
        with closing(sqlite3.connect(self.db_path)) as conn:
            cursor = conn.executemany(
                """
                INSERT OR IGNORE INTO historical_markets (
                    market_id, slug, question, description, category,
                    end_date, closed_time, volume,
                    yes_token_id, no_token_id,
                    outcome_yes, outcome_no,
                    event_type, platform, raw_json
                ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                rows,
            )
            conn.commit()
            return cursor.rowcount

    def load_markets(self, with_outcome_only: bool = True) -> list[dict[str, Any]]:
        """Return all historical_markets rows as dicts."""
        query = "SELECT * FROM historical_markets"
        if with_outcome_only:
            query += " WHERE outcome_yes IS NOT NULL"
        query += " ORDER BY end_date"
        with closing(sqlite3.connect(self.db_path)) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute(query).fetchall()
            return [dict(row) for row in rows]

    def market_ids_with_prices(self) -> set[str]:
        """Return market IDs that already have price data."""
        with closing(sqlite3.connect(self.db_path)) as conn:
            rows = conn.execute(
                "SELECT DISTINCT market_id FROM historical_prices"
            ).fetchall()
            return {row[0] for row in rows}

    def update_market_event_type(self, market_id: str, event_type: str, platform: str) -> None:
        with closing(sqlite3.connect(self.db_path)) as conn:
            conn.execute(
                "UPDATE historical_markets SET event_type=?, platform=? WHERE market_id=?",
                (event_type, platform, market_id),
            )
            conn.commit()

    # -----------------------------------------------------------------------
    # historical_prices
    # -----------------------------------------------------------------------

    def insert_prices(
        self,
        market_id: str,
        token_side: str,
        bars: list[HistoricalPriceBar],
    ) -> int:
        """Insert price bars, ignoring duplicates. Returns inserted count."""
        rows = [
            (
                market_id,
                token_side,
                bar.timestamp_utc.isoformat(),
                bar.open_price,
                bar.high_price,
                bar.low_price,
                bar.close_price,
            )
            for bar in bars
        ]
        with closing(sqlite3.connect(self.db_path)) as conn:
            cursor = conn.executemany(
                """
                INSERT OR IGNORE INTO historical_prices
                (market_id, token_side, timestamp_utc,
                 open_price, high_price, low_price, close_price)
                VALUES (?,?,?,?,?,?,?)
                """,
                rows,
            )
            conn.commit()
            return cursor.rowcount

    def load_prices(
        self,
        market_id: str,
        token_side: str,
    ) -> list[dict[str, Any]]:
        """Load all price bars for a given market and side."""
        with closing(sqlite3.connect(self.db_path)) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                """
                SELECT timestamp_utc, open_price, high_price, low_price, close_price
                FROM historical_prices
                WHERE market_id = ? AND token_side = ?
                ORDER BY timestamp_utc
                """,
                (market_id, token_side),
            ).fetchall()
            return [dict(row) for row in rows]

    def load_price_pairs(
        self,
        market_id: str,
    ) -> list[tuple[str, float, float]]:
        """
        Return (timestamp_utc, yes_close, no_close) tuples for a market.
        Only timestamps where both YES and NO prices exist are returned.
        """
        with closing(sqlite3.connect(self.db_path)) as conn:
            rows = conn.execute(
                """
                SELECT y.timestamp_utc, y.close_price as yes_close, n.close_price as no_close
                FROM historical_prices y
                JOIN historical_prices n
                  ON y.market_id = n.market_id AND y.timestamp_utc = n.timestamp_utc
                WHERE y.market_id = ? AND y.token_side = 'yes' AND n.token_side = 'no'
                ORDER BY y.timestamp_utc
                """,
                (market_id,),
            ).fetchall()
            return [(row[0], float(row[1]), float(row[2])) for row in rows]

    def load_yes_prices(self, market_id: str) -> list[tuple[str, float]]:
        """Return (timestamp_utc, yes_close) for markets with only YES token data."""
        with closing(sqlite3.connect(self.db_path)) as conn:
            rows = conn.execute(
                """
                SELECT timestamp_utc, close_price
                FROM historical_prices
                WHERE market_id = ? AND token_side = 'yes'
                ORDER BY timestamp_utc
                """,
                (market_id,),
            ).fetchall()
            return [(row[0], float(row[1])) for row in rows]

    # -----------------------------------------------------------------------
    # historical_snapshots
    # -----------------------------------------------------------------------

    def insert_snapshots(self, snapshots: list[dict[str, Any]]) -> int:
        """Insert or replace historical snapshots. Returns inserted count."""
        rows = [
            (
                str(snap.get("market_id") or ""),
                str(snap.get("slug") or ""),
                str(snap.get("timestamp_utc") or ""),
                _float_or_none(snap.get("days_before_close")),
                str(snap.get("event_type") or ""),
                str(snap.get("platform") or ""),
                _float_or_none(snap.get("yes_mid")),
                _float_or_none(snap.get("no_mid")),
                _float_or_none(snap.get("yes_ask")),
                _float_or_none(snap.get("no_ask")),
                _float_or_none(snap.get("yes_bid")),
                _float_or_none(snap.get("no_bid")),
                _float_or_none(snap.get("spread")),
                _float_or_none(snap.get("p_model")),
                str(snap.get("model_side") or ""),
                _float_or_none(snap.get("net_edge")),
                _float_or_none(snap.get("max_entry_price")),
                1 if snap.get("market_ok") else 0,
                1 if snap.get("signal_ok") else 0,
                _float_or_none(snap.get("outcome_yes")),
                _float_or_none(snap.get("outcome_no")),
                json.dumps(snap, ensure_ascii=True),
            )
            for snap in snapshots
        ]
        with closing(sqlite3.connect(self.db_path)) as conn:
            cursor = conn.executemany(
                """
                INSERT OR REPLACE INTO historical_snapshots (
                    market_id, slug, timestamp_utc, days_before_close,
                    event_type, platform,
                    yes_mid, no_mid, yes_ask, no_ask, yes_bid, no_bid, spread,
                    p_model, model_side, net_edge, max_entry_price,
                    market_ok, signal_ok,
                    outcome_yes, outcome_no, raw_json
                ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                rows,
            )
            conn.commit()
            return cursor.rowcount

    def load_snapshots(
        self,
        with_outcome_only: bool = True,
        market_ok_only: bool = True,
    ) -> list[dict[str, Any]]:
        """Load historical snapshots for backtest/calibration consumption."""
        conditions: list[str] = []
        if with_outcome_only:
            conditions.append("outcome_yes IS NOT NULL")
        if market_ok_only:
            conditions.append("market_ok = 1")
        where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
        with closing(sqlite3.connect(self.db_path)) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                f"SELECT * FROM historical_snapshots {where} ORDER BY timestamp_utc"
            ).fetchall()
            return [dict(row) for row in rows]

    def snapshot_count(self) -> int:
        with closing(sqlite3.connect(self.db_path)) as conn:
            row = conn.execute("SELECT COUNT(*) FROM historical_snapshots").fetchone()
            return int(row[0]) if row else 0

    def market_count(self) -> int:
        with closing(sqlite3.connect(self.db_path)) as conn:
            row = conn.execute("SELECT COUNT(*) FROM historical_markets").fetchone()
            return int(row[0]) if row else 0

    def price_bar_count(self) -> int:
        with closing(sqlite3.connect(self.db_path)) as conn:
            row = conn.execute("SELECT COUNT(*) FROM historical_prices").fetchone()
            return int(row[0]) if row else 0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _iso(dt: datetime | None) -> str | None:
    if dt is None:
        return None
    return dt.astimezone(timezone.utc).isoformat()


def _float_or_none(value: object) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None
